# Generated by Django 5.1.7 on 2025-04-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, null=True)),
                ('line_id', models.CharField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
