# Generated by Django 5.1.7 on 2025-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whats_app_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
