# Generated by Django 5.1.7 on 2025-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0004_contact_whats_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
