# Generated by Django 5.1.7 on 2025-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linenotify', '0005_contact_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='task_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
